[body]
density = 533                           # https://sci.esa.int/web/rosetta/-/14615-comet-67p
mu = 665.666                            # Gravitational parameter for 67P/C-G.
declination = 64                        # [degrees] https://sci.esa.int/web/rosetta/-/14615-comet-67p
right_ascension = 69                    # [degrees] https://sci.esa.int/web/rosetta/-/14615-comet-67p
spin_period = 43416                     # 12.06h * 3600 [seconds] https://sci.esa.int/web/rosetta/-/14615-comet-67p

[integrator]
algorithm = 3                           # Integration algorithm, see:  "toss/Integrator.py".
dense_output = true                     # Interpolates between integration steps and enable computation of arbitrary points on time-interval.
rtol = 1e-12                            # Relative tolerance for chosen integration algorithm.
atol = 1e-12                            # Absolute tolerance for chosen integration algorithm.

[problem]
start_time = 0                          # Starting time [seconds].
final_time = 72000                      # (20h*3600) Final time [seconds].
initial_time_step = 600                 # Initial time step size for integration [seconds].
radius_bounding_sphere = 4000           # Radius of spherical risk-zone for collision with celestial body [meter].
target_squared_altitude = 64000000      # (8000**2) Target altitude squared [meter].
activate_event = true                   # Event configuration (False = no events, True = collision with body detection).
number_of_maneuvers = 0                 # Maximum number of possible manuevers during mission.
max_velocity_scaling_factor = 40        # Scales the magnitude of the fixed-valued maximal velocity, and therefore also the grid spacing.
penalty_scaling_factor = 1              # Appropriately chosen scaling for the penalty values (P=[0,1]) to be comparable with the magnitude of covered space ratio. 

[optimization]          
population_size = 80                    # Number of chromosomes for the pygmo-based optimization.
number_of_generations = 30              # Number of generations for evolutionary optimization process.
number_of_islands = 40                  # Number of threads for parallelliztion of the optimization process (Reasonably a multiple of population size).

[algorithm]
kernel_size = 13
convergence_speed_parameter = 1.0
oracle_parameter = 1e9
accuracy_parameter = 0.0
threshold_parameter = 1
std_convergence_speed_parameter = 7
improvement_stopping_criterion = 100000
evaluation_stopping_criterion = 100000
focus_parameter = 0.0
memory_parameter = false

[mesh]
mesh_path = "3dmeshes/churyumov-gerasimenko_lp.pk"