[body]
density = 533                           # https://sci.esa.int/web/rosetta/-/14615-comet-67p
mu = 665.666                            # Gravitational parameter for 67P/C-G.
declination = 64                        # [degrees] https://sci.esa.int/web/rosetta/-/14615-comet-67p
right_ascension = 69                    # [degrees] https://sci.esa.int/web/rosetta/-/14615-comet-67p
spin_period = 43416                     # 12.06h * 3600 [seconds] https://sci.esa.int/web/rosetta/-/14615-comet-67p
spin_axis_x = 0
spin_axis_y = 0
spin_axis_z = 1

[integrator]
algorithm = 3                           # Integration algorithm, see:  "toss/Integrator.py".
dense_output = true                     # Interpolates between integration steps and enable computation of arbitrary points on time-interval.
rtol = 1e-12                            # Relative tolerance for chosen integration algorithm.
atol = 1e-12                            # Absolute tolerance for chosen integration algorithm.
parallel_acceleration_computation = false # Compute accelerations using polyhedral-model in parallel setting.

[problem]
start_time = 0                          # Starting time [seconds].
final_time = 604800                     # (20h*3600) Final time [seconds].
initial_time_step = 1                   # Initial time step size for integration [seconds].
activate_event = true                   # Event configuration (False = no events, True = collision with body detection).
number_of_maneuvers = 2                 # Maximum number of possible manuevers during mission.
number_of_spacecrafts = 4
target_squared_altitude = 16000000      # (8000**2) Target altitude squared [meter].
activate_rotation = true                # Toggles rotation of the body.
measurement_period = 100                # Period for when a measurement sphere is recognized and managed. Unit: [seconds]
radius_inner_bounding_sphere = 4000     # Radius of spherical risk-zone for collision with celestial body [m]
radius_outer_bounding_sphere = 12500    # Radius of spherical outer boundary sphere with celestial body [m]
max_velocity_scaling_factor = 40        # Scales the magnitude of the fixed-valued maximal velocity, and therefore also the grid spacing.
penalty_scaling_factor = 0.1            # Appropriately chosen scaling for the penalty values (P=[0,1]) to be comparable with the magnitude of covered space ratio. 
maximal_measurement_sphere_radius = 35.95398913 # Radius found at point of greatest gravitational influence by the body for a spacecraft on the boundary of the inner bounding sphere with measurement period of 100 [s].
sample_vx = -0.02826052                 # Sample velocity for a previous trajectory around the body minimizing distance to safety radius.
sample_vy = 0.1784372
sample_vz = -0.29885126
initial_x = -135.13402075               # Assumption on initial state: position
initial_y = -4089.53592604
initial_z = 6050.17636635
initial_vx = 0                          # Assumption on initial state: velocity
initial_vy = 0
initial_vz = 0

[optimization]          
population_size = 15                    # Number of chromosomes for the pygmo-based optimization.
number_of_generations = 15              # Number of generations for evolutionary optimization process.
number_of_threads = 5                   # Number of threads for parallelliztion of the optimization process (Reasonably a multiple of population size).

[chromosome]
x_min = 0
y_min = 0
z_min = 0
x_max = 0
y_max = 0
z_max = 0
dv_min = 0
dv_max = 2.5
dvx_min = -1
dvy_min = -1
dvz_min = -1
dvx_max = 1
dvy_max = 1
dvz_max = 1
v_min = 0
v_max = 1
vx_min = -1
vy_min = -1
vz_min = -1
vx_max = 1
vy_max = 1
vz_max = 1

[algorithm]
kernel_size = 13
convergence_speed_parameter = 1.0
oracle_parameter = 1e9
accuracy_parameter = 0.0
threshold_parameter = 1
std_convergence_speed_parameter = 7
improvement_stopping_criterion = 100000
evaluation_stopping_criterion = 100000
focus_parameter = 0.0
memory_parameter = false

[mesh]
mesh_path = "3dmeshes/churyumov-gerasimenko_llp.pk"